In [6]:
import pandas as pd
import numpy as np

local_doc = pd.read_excel(".\data\local_doc_1000.xlsx")
x_year = local_doc['year']
y_total = local_doc['합계']
y_seoul = local_doc['서울']
y_pusan = local_doc['부산']
y_daegu =local_doc['대구']
y_Incheon =local_doc['인천']
y_guangju = local_doc['광주']
y_daejoen = local_doc['대전']
y_ulsan = local_doc['울산']
y_sejong = local_doc['세종']
y_gyeonggi = local_doc['경기']
y_kangwon = local_doc['강원']
y_choungbuk = local_doc['충북']
y_choungnam = local_doc['충남']
y_jeonbuk = local_doc['전북']
y_jeonnam = local_doc['전남']
y_gyeongbuk = local_doc['경북']
y_gyeongnam = local_doc['경남']
y_jeju = local_doc['제주']

## OECD 평균

In [17]:
import pandas as pd

data_df = pd.read_excel('.\data\OECD의사수.xlsx')
# Variable 0:Practising physicians / 1:Professionally active physicians / 2:Physicians licensed to practice
# Measure 0:Number of persons (head counts) / 1: Density per 1 000 population (head counts)
# OECD 0: OECD Economies / 1: Non-OECD Economies
data_df

Variable  Measure  OECD         Country      2000      2001      2002  \
0           0        0     1       Australia  47372.00  49392.00  49895.00   
1           0        0     1         Austria  30871.00  31859.00  32575.00   
2           0        0     1         Belgium  28999.00  29303.00  29537.00   
3           0        0     1          Canada  61748.00  62488.00  63498.00   
4           0        0     1        Colombia  49406.00  51209.00  53266.00   
..        ...      ...   ...             ...       ...       ...       ...   
181         2        1     1        Portugal      3.08      3.13      3.16   
182         2        1     1           Spain      4.41      4.42      4.49   
183         2        1     1          Sweden      4.19      4.31      4.44   
184         2        1     1  United Kingdom      3.43      3.48      3.52   
185         2        1     1   United States      2.88      2.93      2.97   

         2003      2004      2005  ...      2010      2011      2012  \
0    51819.00  53966.00  56084.00  ...       NaN  74100.00  75258.00   
1    33410.00  34334.00  35518.00  ...  40105.00  40634.00  41268.00   
2    29646.00  29891.00  30081.00  ...  31815.00  32182.00  32583.00   
3    63780.00  65301.00  66688.00  ...  77488.00  80762.00  83629.00   
4    55332.00  57774.00  60331.00  ...  74584.00  78221.30  81739.53   
..        ...       ...       ...  ...       ...       ...       ...   
181      3.22      3.28      3.36  ...      3.85      3.98      4.10   
182      4.52      4.54      4.56  ...      4.80      4.84      4.89   
183      4.59      4.75      4.91  ...      5.68      5.84      6.00   
184      3.74      3.85      3.96  ...      3.61      3.68      3.71   
185      3.00      3.02      3.05  ...      3.19      3.22      3.27   

         2013      2014      2015      2016       2017       2018       2019  
0    77974.00  80968.00  83490.00  86550.00   90417.00   93604.00        NaN  
1    42302.00  43126.00  44002.00  44816.00   45596.00   46337.00        NaN  
2    32999.00  33353.00  34020.00  34834.00   35069.00   35762.00        NaN  
3    86406.00  88873.00  91268.00  94643.00   97213.00  100845.00  103020.00  
4    85694.36  90085.25  93815.37  97965.63  103025.77  108499.30        NaN  
..        ...       ...       ...       ...        ...        ...        ...  
181      4.26      4.43      4.61      4.80       4.97       5.15        NaN  
182      4.99      5.13      5.23      5.33       5.45       5.57        NaN  
183      6.16      6.32      6.48      6.58       6.68       6.79        NaN  
184      3.72      3.67      3.60      3.62       3.67       3.76       3.91  
185      3.31      3.35      3.39      3.43       3.47       3.49        NaN  

[186 rows x 24 columns]

In [36]:
year = np.array(data_df.T.index[4:])
year = year.reshape(-1, 1)

In [8]:
meanData_df = data_df.groupby(['Variable','Measure','OECD']).mean()
y2 = meanData_df.iloc[3]
y2

2000    2.685667
2001    2.732414
2002    2.749333
2003    2.847667
2004    2.864839
2005    2.908966
2006    2.939000
2007    3.004138
2008    3.028667
2009    3.087931
2010    3.082069
2011    3.149333
2012    3.150645
2013    3.229333
2014    3.250968
2015    3.321724
2016    3.346333
2017    3.436207
2018    3.500000
2019    3.651667
Name: (0, 1, 1), dtype: float64

In [10]:
import plotly.graph_objects as go
# Create traces
fig = go.Figure()

yearList = list(range(2000,2020))

fig.add_trace(go.Scatter(x=yearList, y=y2, 
                        mode='lines+markers',
                        name='OECD 평균')),

fig.add_trace(go.Scatter(x= x_year, y=y_total,
                        mode='lines+markers',
                        name='전국'))
fig.add_trace(go.Scatter(x= x_year, y=y_seoul,
                        mode='lines+markers',
                        name='서울'))
fig.add_trace(go.Scatter(x= x_year, y=y_pusan,
                        mode='lines+markers',
                        name='부산'))

fig.add_trace(go.Scatter(x= x_year, y=y_daegu,
                        mode='lines+markers',
                        name='대구'))
fig.add_trace(go.Scatter(x= x_year, y=y_Incheon,
                        mode='lines+markers',
                        name='인천'))
fig.add_trace(go.Scatter(x=x_year, y=y_guangju,
                        mode='lines+markers',
                        name='광주'))

fig.add_trace(go.Scatter(x=x_year, y=y_daejoen,
                        mode='lines+markers',
                        name='대전'))
fig.add_trace(go.Scatter(x=x_year, y=y_ulsan,
                        mode='lines+markers',
                        name='울산'))
fig.add_trace(go.Scatter(x=x_year, y=y_sejong,
                        mode='lines+markers',
                        name='세종'))

fig.add_trace(go.Scatter(x=x_year, y=y_gyeonggi,
                        mode='lines+markers',
                        name='경기'))
fig.add_trace(go.Scatter(x=x_year, y=y_kangwon,
                        mode='lines+markers',
                        name='강원'))
fig.add_trace(go.Scatter(x=x_year, y=y_choungbuk,
                        mode='lines+markers',
                        name='충북'))

fig.add_trace(go.Scatter(x=x_year, y=y_choungnam,
                        mode='lines+markers',
                        name='충남'))
fig.add_trace(go.Scatter(x=x_year, y=y_jeonbuk,
                        mode='lines+markers',
                        name='전북'))
fig.add_trace(go.Scatter(x=x_year, y=y_jeonnam,
                        mode='lines+markers',
                        name='전남'))

fig.add_trace(go.Scatter(x=x_year, y=y_gyeongbuk,
                        mode='lines+markers',
                        name='경북'))
fig.add_trace(go.Scatter(x=x_year, y=y_gyeongnam,
                        mode='lines+markers',
                        name='경남'))
fig.add_trace(go.Scatter(x=x_year, y=y_jeju,
                        mode='lines+markers',
                        name='제주'))
fig.update_layout(
    title_text="1000명당 의료 인력", height=650
    )

fig.show()

## OECD 회귀분석

In [135]:
import numpy as np
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [157]:
line_fitter = LinearRegression()
X = year
y = y2
line_fitter.fit(X, y)
y_predicted = line_fitter.predict(X)
y_predicted

array([2.67396283, 2.71863464, 2.76330644, 2.80797825, 2.85265006,
       2.89732186, 2.94199367, 2.98666548, 3.03133728, 3.07600909,
       3.1206809 , 3.1653527 , 3.21002451, 3.25469632, 3.29936812,
       3.34403993, 3.38871174, 3.43338354, 3.47805535, 3.52272716])

In [158]:
y = list(y2)
y

[2.6856666666666675,
 2.7324137931034485,
 2.749333333333333,
 2.847666666666667,
 2.8648387096774193,
 2.9089655172413793,
 2.939000000000001,
 3.004137931034483,
 3.0286666666666666,
 3.0879310344827586,
 3.082068965517242,
 3.149333333333333,
 3.1506451612903232,
 3.2293333333333334,
 3.250967741935484,
 3.321724137931034,
 3.3463333333333343,
 3.4362068965517234,
 3.5000000000000004,
 3.651666666666667]

In [159]:
line_fitter.predict([[2020]])

array([3.56739896])

In [160]:
line_fitter.predict([[2030]])

array([4.01411703])

In [161]:
gradient = line_fitter.coef_ #기울기
gradient = gradient[0]
type(gradient)

numpy.float64

In [162]:
bias = line_fitter.intercept_ #절편
bias

-86.66965037259445

In [163]:
a = X.T
a = a[0]
a = list(a)
y_predicted = list(y_predicted)

for i in range(2020, 2040):
    a.append(str(i))
    y_predicted.append(float(line_fitter.predict([[i]])))

    
y_predicted

[2.6739628317177733,
 2.7186346383199265,
 2.763306444922094,
 2.807978251524247,
 2.8526500581264003,
 2.8973218647285535,
 2.9419936713307067,
 2.986665477932874,
 3.0313372845350273,
 3.0760090911371805,
 3.1206808977393337,
 3.165352704341487,
 3.2100245109436543,
 3.2546963175458075,
 3.2993681241479607,
 3.344039930750114,
 3.388711737352267,
 3.4333835439544345,
 3.4780553505565877,
 3.522727157158741,
 3.567398963760894,
 3.6120707703630472,
 3.6567425769652147,
 3.701414383567368,
 3.746086190169521,
 3.7907579967716742,
 3.8354298033738274,
 3.880101609975995,
 3.924773416578148,
 3.9694452231803012,
 4.014117029782454,
 4.058788836384622,
 4.103460642986775,
 4.148132449588928,
 4.192804256191081,
 4.237476062793235,
 4.282147869395402,
 4.326819675997555,
 4.371491482599708,
 4.416163289201862]

In [133]:
yList = []
for i in range(len(a)):
    yList.append((i*gradient)+2.68)
yList

[2.68,
 2.7246718066021565,
 2.7693436132043123,
 2.8140154198064686,
 2.8586872264086245,
 2.903359033010781,
 2.9480308396129367,
 2.992702646215093,
 3.0373744528172493,
 3.082046259419405,
 3.1267180660215614,
 3.1713898726237173,
 3.2160616792258736,
 3.2607334858280295,
 3.3054052924301858,
 3.350077099032342,
 3.394748905634498,
 3.439420712236654,
 3.48409251883881,
 3.5287643254409664]

In [164]:
import plotly.graph_objects as go
import numpy as np



fig = go.Figure()

fig.add_trace(go.Scatter(x=a, y=y,
                    mode='markers',
                    name='lines'))
fig.add_trace(go.Scatter(x = a, y = y_predicted, 
                         mode = 'lines+markers',
                         name = 'regression'))


# fig = go.Figure(data=go.Scatter(x=X, y=line_fitter.predict(X)))
fig.show()