In [3]:
from __future__ import print_function
import torch
import numpy as np

## 2.2.1 텐서를 만드는 법

### 1. torch.Tensor 함수로 Numpy와 리스트 객체로부터 텐서를 생성할 수 있음

In [5]:
# list로부터 2x3 텐서 생성
x_list = [[1,2,3],[4,5,6]]
x = torch.Tensor(x_list)
print(x)


tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
#numpy array로부터 2x3텐서 생성
x_numpy = np.array([[1,2,3],[4,5,6]])
print(x_numpy)

[[1 2 3]
 [4 5 6]]


In [11]:
x = torch.Tensor(np.array([[9,6,1],[5,3,2]]))
print(x)

tensor([[9., 6., 1.],
        [5., 3., 2.]])


### .tolist() 혹은 .numpy()명령어를 통해 다시 원래의 자료구조로 만들 수 있음

In [14]:
#.tolist()
x_back2list = x.tolist()
print(type(x_back2list))
print(x_back2list)

<class 'list'>
[[9.0, 6.0, 1.0], [5.0, 3.0, 2.0]]


In [17]:
#.numpy()
x_back2numpy = x.tolist()
print(x_back2numpy)
print(type(x_back2numpy))

[[9.0, 6.0, 1.0], [5.0, 3.0, 2.0]]
<class 'list'>


#### 기본적으로 텐서 생성 시 CPU 상태 디바이스 정보를 가지고 있으며,
#### '.device'속성을 조회하면 현재 사용하고 있는 디바이스 정보를 알 수 있다.
* GPU 텐서를 만드는 방법은 텐서에서 '.to'함수를 호출 시 'cuda'라는 문자열 인자를 전달하거나 '.cuda()'함수를 호출한다.
* 만약에 CPU를 다시 사용하고 싶다면 다시 'cpu'문자열을 .to()함수에 전달하거나 '.cpu()'함수를 호출

In [18]:
#기본 device정보
print(x.device)

cpu


In [19]:
device = 'cuda'

In [21]:
#GPU사용
x = x.to(device)
print(device)

RuntimeError: CUDA error: out of memory