In [1]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5,3)
x

tensor([[ 5.5397e+23,  4.5907e-41,  5.5397e+23],
        [ 4.5907e-41,  4.4842e-44,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00,  1.1870e-36],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00],
        [-9.9915e+11,  7.5511e-18,  2.8382e+22]])

In [5]:
x = torch.rand(5,3)
x

tensor([[0.7952, 0.9378, 0.9660],
        [0.2170, 0.3244, 0.5215],
        [0.7851, 0.9634, 0.9089],
        [0.7459, 0.6820, 0.6300],
        [0.9608, 0.2283, 0.8654]])

In [9]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.8391,  0.5977, -0.5857],
        [ 2.0228, -2.1337, -0.5396],
        [ 1.0860,  0.5700, -1.2602],
        [-0.6086,  0.1077, -0.4992],
        [ 0.0781,  0.1111, -0.0129]])

In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
x.size()

torch.Size([5, 3])

In [24]:
y = torch.rand(5,3)
x+y

tensor([[ 2.5468,  0.6372,  0.3659],
        [ 2.6830, -2.0242, -0.4491],
        [ 1.7546,  0.9884, -0.7328],
        [-0.1618,  0.8285, -0.0394],
        [ 0.2492,  0.8334,  0.5139]])

In [25]:
x

tensor([[ 1.8391,  0.5977, -0.5857],
        [ 2.0228, -2.1337, -0.5396],
        [ 1.0860,  0.5700, -1.2602],
        [-0.6086,  0.1077, -0.4992],
        [ 0.0781,  0.1111, -0.0129]])

In [26]:
y

tensor([[0.7077, 0.0395, 0.9515],
        [0.6602, 0.1095, 0.0904],
        [0.6686, 0.4184, 0.5274],
        [0.4468, 0.7208, 0.4597],
        [0.1711, 0.7222, 0.5267]])

In [27]:
torch.add(x,y)

tensor([[ 2.5468,  0.6372,  0.3659],
        [ 2.6830, -2.0242, -0.4491],
        [ 1.7546,  0.9884, -0.7328],
        [-0.1618,  0.8285, -0.0394],
        [ 0.2492,  0.8334,  0.5139]])

In [28]:
result = torch.empty(5,3)

In [29]:
torch.add(x,y,out=result)
result

tensor([[ 2.5468,  0.6372,  0.3659],
        [ 2.6830, -2.0242, -0.4491],
        [ 1.7546,  0.9884, -0.7328],
        [-0.1618,  0.8285, -0.0394],
        [ 0.2492,  0.8334,  0.5139]])

In [32]:
y.add_(x) # add는 더하기 add_는 더해서 바꿔치기
y

tensor([[ 2.5468,  0.6372,  0.3659],
        [ 2.6830, -2.0242, -0.4491],
        [ 1.7546,  0.9884, -0.7328],
        [-0.1618,  0.8285, -0.0394],
        [ 0.2492,  0.8334,  0.5139]])

In [33]:
x

tensor([[ 1.8391,  0.5977, -0.5857],
        [ 2.0228, -2.1337, -0.5396],
        [ 1.0860,  0.5700, -1.2602],
        [-0.6086,  0.1077, -0.4992],
        [ 0.0781,  0.1111, -0.0129]])

In [35]:
x[:,2] #모든 행 세번째 컬럼

tensor([-0.5857, -0.5396, -1.2602, -0.4992, -0.0129])

In [39]:
x[:2,2] #세번째 컬럼의 두번째 행까지

tensor([-0.5857, -0.5396])

In [42]:
x[1:2] # 첫째에서 둘째 행

tensor([[ 2.0228, -2.1337, -0.5396]])

In [43]:
x = torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)

In [44]:
x

tensor([[ 1.0055, -0.1857,  1.1506,  1.4947],
        [ 0.5543, -0.1376, -2.6873,  1.7480],
        [-0.4733,  0.3533, -1.2724, -0.2495],
        [ 0.6680, -1.4111,  1.0482,  0.7307]])

In [45]:
y

tensor([ 1.0055, -0.1857,  1.1506,  1.4947,  0.5543, -0.1376, -2.6873,  1.7480,
        -0.4733,  0.3533, -1.2724, -0.2495,  0.6680, -1.4111,  1.0482,  0.7307])

In [46]:
z

tensor([[ 1.0055, -0.1857,  1.1506,  1.4947,  0.5543, -0.1376, -2.6873,  1.7480],
        [-0.4733,  0.3533, -1.2724, -0.2495,  0.6680, -1.4111,  1.0482,  0.7307]])

In [48]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [54]:
x = torch.randn(1)
x

tensor([-0.3353])

In [57]:
x.item()

-0.33527475595474243

In [61]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [62]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [63]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [64]:
print(b)

[2. 2. 2. 2. 2.]


In [65]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [69]:
np.add(a,1,out=a)

array([3., 3., 3., 3., 3.])

In [70]:
a

array([3., 3., 3., 3., 3.])

In [71]:
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [72]:
x = torch.ones(2,2,requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [74]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [75]:
y.grad_fn

In [76]:
z = y*y*3
out = z.mean()

In [78]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [80]:
a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a.requires_grad)

False


In [81]:
a.requires_grad_(True)

tensor([[ 0.7642, -1.6533],
        [ 1.3522, 41.3107]], requires_grad=True)

In [82]:
b=(a*a).sum()
print(b,b.grad_fn)

tensor(1711.7227, grad_fn=<SumBackward0>) <SumBackward0 object at 0x7ff7982c28d0>


In [83]:
out.backward()

In [84]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [85]:
x = torch.randn(3,requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y= y*2
print(y)

tensor([  871.8969, -1383.1259,   -29.9491], grad_fn=<MulBackward0>)


In [86]:
v = torch.tensor([0.1,1.0,.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [89]:
print(x.requires_grad)
y=x.detach()

True


In [90]:
y

tensor([ 1.7029, -2.7014, -0.0585])

In [91]:
print(y.requires_grad)
print(x.eq(y).all())

False
tensor(True)


## 신경망

In [93]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 입력 이미지 채널 1개, 출력 채널 6개, 3x3의 정사각 컨볼루션 행렬
        # 컨볼루션 커널 정의
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # 아핀(affine) 연산: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6은 이미지 차원에 해당
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # (2, 2) 크기 윈도우에 대해 맥스 풀링(max pooling)
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # 크기가 제곱수라면 하나의 숫자만을 특정
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # 배치 차원을 제외한 모든 차원
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
