In [18]:
from __future__ import print_function
import torch
import numpy as np

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.8546e-24, 4.5869e-41, 1.7016e-36],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.2646e+22, 7.2250e+28],
        [2.5226e-18, 2.4283e-18, 2.6302e+20]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3516, 0.4778, 0.5416],
        [0.2648, 0.6085, 0.4421],
        [0.1576, 0.1485, 0.9190],
        [0.4084, 0.7367, 0.7415],
        [0.4866, 0.1754, 0.0201]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.1761, -0.4217,  0.7376],
        [ 0.4637,  0.3145, -0.6242],
        [ 0.4990, -2.1738, -0.4349],
        [-0.4305, -0.7896,  1.2370],
        [ 0.7055, -0.7170,  0.4646]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [56]:
x = torch.empty(1000, 1000)
y = torch.empty(1000, 1000)
%time x*y
a = np.empty([1000, 1000])
b = np.empty([1000, 1000])
%time a*b

CPU times: user 86.3 ms, sys: 0 ns, total: 86.3 ms
Wall time: 6.71 ms
CPU times: user 58.1 ms, sys: 0 ns, total: 58.1 ms
Wall time: 4.72 ms


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
a = np.empty([1000, 1000])
b = np.empty([1000, 1000])
%time a*b

CPU times: user 0 ns, sys: 8.85 ms, total: 8.85 ms
Wall time: 6.65 ms


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
cuda = torch.device('cuda:1')
cuda

device(type='cuda', index=1)

In [81]:
x = torch.empty([1000, 1000], device=cuda)
y = torch.empty([1000, 1000], device=cuda)
%time x*y
a = np.empty([1000, 1000])
b = np.empty([1000, 1000])
%time a*b

CPU times: user 223 µs, sys: 62 µs, total: 285 µs
Wall time: 164 µs
CPU times: user 3.03 ms, sys: 4.19 ms, total: 7.23 ms
Wall time: 6.46 ms


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])